#!/bin/bash
# Quick reference: Setting up automatic Pachyderm → Airflow triggering
# 
# This file contains the essential commands to get automatic DAG triggering working.

echo "=== QUICK START: Pachyderm → Airflow Webhook Setup ==="
echo ""

# STEP 1: Deploy webhook listener
echo "Step 1: Deploy webhook listener in Airflow namespace"
echo "  Command: kubectl apply -f pipelines/airflow/webhook-deployment.yaml"
echo ""

# STEP 2: Verify deployment
echo "Step 2: Verify webhook pod is running"
echo "  Command: kubectl -n airflow get pods -l app=pachyderm-webhook"
echo "  Expected: 2 pods in Running state"
echo ""

# STEP 3: Configure Pachyderm notification
echo "Step 3: Create Pachyderm notification rule"
echo "  Command: bash pipelines/airflow/setup-pachyderm-notification.sh"
echo "  Or manually:"
echo "    pachctl notification create \\"
echo "      --name ingest-pipeline-trigger \\"
echo "      --repo media \\"
echo "      --branch master \\"
echo "      --trigger commit \\"
echo "      --webhook-url http://pachyderm-webhook.airflow:8000/webhook/pachyderm"
echo ""

# STEP 4: Test the integration
echo "Step 4: Test by uploading a file"
echo "  1. Create test video:"
echo "     ffmpeg -f lavfi -i testsrc=s=640x480:d=1 -f lavfi -i sine=f=1000:d=1 /tmp/test.mp4"
echo ""
echo "  2. Upload to Pachyderm:"
echo "     pachctl put file media@master:/incoming/test-001/test.mp4 -f /tmp/test.mp4"
echo ""
echo "  3. Watch webhook logs (in new terminal):"
echo "     kubectl -n airflow logs -l app=pachyderm-webhook -f"
echo ""
echo "  4. Check Airflow for new DAG run:"
echo "     kubectl -n airflow port-forward svc/airflow-webserver 8080:8080"
echo "     Open: http://localhost:8080/dags/ingest_pipeline/grid"
echo ""

echo "=== MONITORING ==="
echo ""
echo "View webhook service:"
echo "  kubectl -n airflow describe svc pachyderm-webhook"
echo ""
echo "Stream webhook logs:"
echo "  kubectl -n airflow logs -l app=pachyderm-webhook -f"
echo ""
echo "Check Pachyderm notifications:"
echo "  pachctl notification list --repo media"
echo ""
echo "Verify Pachyderm can reach webhook (from pachd pod):"
echo "  kubectl -n pachyderm exec <pachd-pod> -- curl -v http://pachyderm-webhook.airflow:8000/health"
echo ""

echo "=== TROUBLESHOOTING ==="
echo ""
echo "Webhook not receiving events?"
echo "  1. Check notification exists: pachctl notification list --repo media"
echo "  2. Check logs: kubectl -n airflow logs -l app=pachyderm-webhook"
echo "  3. Test connectivity: kubectl -n pachyderm exec <pachd-pod> -- curl http://pachyderm-webhook.airflow:8000/health"
echo ""

echo "DAG not triggering?"
echo "  1. Check webhook logs for errors: kubectl -n airflow logs -l app=pachyderm-webhook"
echo "  2. Check Airflow API: kubectl -n airflow port-forward svc/airflow-webserver 8080:8080"
echo "     curl http://localhost:8080/api/v1/dags"
echo "  3. Verify DAG syntax: kubectl -n airflow exec <airflow-pod> -- airflow dags test ingest_pipeline"
echo ""

echo "=== CONFIGURATION ==="
echo ""
echo "Webhook settings (edit ConfigMap):"
echo "  kubectl -n airflow edit configmap pachyderm-webhook-config"
echo ""
echo "Webhook code (edit ConfigMap):"
echo "  kubectl -n airflow edit configmap webhook-listener-code"
echo ""
echo "Then restart pods:"
echo "  kubectl -n airflow delete pods -l app=pachyderm-webhook"
echo ""

echo "=== DOCUMENTATION ==="
echo ""
echo "For detailed setup and troubleshooting, see:"
echo "  pipelines/airflow/WEBHOOK_SETUP.md"
echo ""
echo "For webhook listener code, see:"
echo "  pipelines/airflow/webhook_listener.py"
echo ""
echo "For Kubernetes manifests, see:"
echo "  pipelines/airflow/webhook-deployment.yaml"
echo ""
