apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3","meta.helm.sh/release-name":"airflow","meta.helm.sh/release-namespace":"airflow"},"creationTimestamp":"2025-10-28T18:40:31Z","generation":5,"labels":{"app.kubernetes.io/managed-by":"Helm","chart":"airflow-1.18.0","component":"scheduler","executor":"LocalExecutor","heritage":"Helm","release":"airflow","tier":"airflow"},"name":"airflow-scheduler","namespace":"airflow","resourceVersion":"8578577","uid":"445a05b3-aee7-46af-ab5f-0edf67860821"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"component":"scheduler","release":"airflow","tier":"airflow"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"checksum/airflow-config":"cd657caf1dfcd1eadbcddaa68c692d5dcc90954f498b3aee7ffd39932fcda7f1","checksum/extra-configmaps":"e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8","checksum/extra-secrets":"e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827","checksum/metadata-secret":"d184a9f38b679b15ada4242a2ceced1045ce612112c631719b4b0ec476e03095","checksum/pgbouncer-config-secret":"1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688","checksum/result-backend-secret":"98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71","cluster-autoscaler.kubernetes.io/safe-to-evict":"true","kubectl.kubernetes.io/restartedAt":"2025-11-01T02:34:45Z"},"creationTimestamp":null,"labels":{"component":"scheduler","release":"airflow","tier":"airflow"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"component":"scheduler"}},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"args":["bash","-c","exec airflow scheduler"],"env":[{"name":"AIRFLOW_CONN_MINIO_S3","value":"aws://pachyderm:pachyderm-secret-key-123456789@/?region_name=us-east-1\u0026extra__aws__endpoint_url=http%3A%2F%2Fminio.minio-tenant%3A80"},{"name":"AWS_ACCESS_KEY_ID","value":"pachyderm"},{"name":"AWS_SECRET_ACCESS_KEY","value":"pachyderm-secret-key-123456789"},{"name":"AIRFLOW__CORE__FERNET_KEY","valueFrom":{"secretKeyRef":{"key":"fernet-key","name":"airflow-fernet-key"}}},{"name":"AIRFLOW_HOME","value":"/opt/airflow"},{"name":"AIRFLOW__CORE__SQL_ALCHEMY_CONN","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW__DATABASE__SQL_ALCHEMY_CONN","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW_CONN_AIRFLOW_DB","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW__API__SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"api-secret-key","name":"airflow-api-secret-key"}}},{"name":"AIRFLOW__API_AUTH__JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt-secret","name":"airflow-jwt-secret"}}}],"image":"apache/airflow:3.1.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["sh","-c","CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \\\nairflow jobs check --job-type SchedulerJob --local\n"]},"failureThreshold":5,"initialDelaySeconds":10,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":20},"name":"scheduler","ports":[{"containerPort":8793,"name":"worker-logs","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}},"startupProbe":{"exec":{"command":["sh","-c","CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \\\nairflow jobs check --job-type SchedulerJob --local\n"]},"failureThreshold":6,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":20},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/airflow/pod_templates/pod_template_file.yaml","name":"config","readOnly":true,"subPath":"pod_template_file.yaml"},{"mountPath":"/opt/airflow/logs","name":"logs"},{"mountPath":"/opt/airflow/airflow.cfg","name":"config","readOnly":true,"subPath":"airflow.cfg"},{"mountPath":"/opt/airflow/config/airflow_local_settings.py","name":"config","readOnly":true,"subPath":"airflow_local_settings.py"},{"mountPath":"/opt/airflow/dags","name":"dags"}]},{"args":["bash","/clean-logs"],"env":[{"name":"AIRFLOW__LOG_RETENTION_DAYS","value":"15"},{"name":"AIRFLOW__LOG_CLEANUP_FREQUENCY_MINUTES","value":"15"},{"name":"AIRFLOW_HOME","value":"/opt/airflow"}],"image":"apache/airflow:3.1.0","imagePullPolicy":"IfNotPresent","name":"scheduler-log-groomer","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/airflow/logs","name":"logs"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"args":["airflow","db","check-migrations","--migration-wait-timeout=60"],"env":[{"name":"AIRFLOW_CONN_MINIO_S3","value":"aws://pachyderm:pachyderm-secret-key-123456789@/?region_name=us-east-1\u0026extra__aws__endpoint_url=http%3A%2F%2Fminio.minio-tenant%3A80"},{"name":"AWS_ACCESS_KEY_ID","value":"pachyderm"},{"name":"AWS_SECRET_ACCESS_KEY","value":"pachyderm-secret-key-123456789"},{"name":"AIRFLOW__CORE__FERNET_KEY","valueFrom":{"secretKeyRef":{"key":"fernet-key","name":"airflow-fernet-key"}}},{"name":"AIRFLOW_HOME","value":"/opt/airflow"},{"name":"AIRFLOW__CORE__SQL_ALCHEMY_CONN","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW__DATABASE__SQL_ALCHEMY_CONN","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW_CONN_AIRFLOW_DB","valueFrom":{"secretKeyRef":{"key":"connection","name":"airflow-metadata"}}},{"name":"AIRFLOW__API__SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"api-secret-key","name":"airflow-api-secret-key"}}},{"name":"AIRFLOW__API_AUTH__JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt-secret","name":"airflow-jwt-secret"}}}],"image":"apache/airflow:3.1.0","imagePullPolicy":"IfNotPresent","name":"wait-for-airflow-migrations","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/airflow/airflow.cfg","name":"config","readOnly":true,"subPath":"airflow.cfg"},{"mountPath":"/opt/airflow/config/airflow_local_settings.py","name":"config","readOnly":true,"subPath":"airflow_local_settings.py"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":0,"runAsUser":50000},"serviceAccount":"airflow-scheduler","serviceAccountName":"airflow-scheduler","terminationGracePeriodSeconds":10,"volumes":[{"configMap":{"defaultMode":420,"name":"airflow-config"},"name":"config"},{"name":"dags","persistentVolumeClaim":{"claimName":"airflow-dags"}},{"emptyDir":{},"name":"logs"}]}}},"status":{"conditions":[{"lastTransitionTime":"2025-11-01T00:50:29Z","lastUpdateTime":"2025-11-01T00:50:29Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-11-01T02:51:42Z","lastUpdateTime":"2025-11-01T02:53:29Z","message":"ReplicaSet \"airflow-scheduler-655584879f\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":5,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  creationTimestamp: "2025-10-28T18:40:31Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.18.0
    component: scheduler
    executor: LocalExecutor
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-scheduler
  namespace: airflow
  resourceVersion: "8580227"
  uid: 445a05b3-aee7-46af-ab5f-0edf67860821
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: scheduler
      release: airflow
      tier: airflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/airflow-config: cd657caf1dfcd1eadbcddaa68c692d5dcc90954f498b3aee7ffd39932fcda7f1
        checksum/extra-configmaps: e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8
        checksum/extra-secrets: e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827
        checksum/metadata-secret: d184a9f38b679b15ada4242a2ceced1045ce612112c631719b4b0ec476e03095
        checksum/pgbouncer-config-secret: 1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688
        checksum/result-backend-secret: 98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        kubectl.kubernetes.io/restartedAt: "2025-11-01T02:34:45Z"
      creationTimestamp: null
      labels:
        component: scheduler
        release: airflow
        tier: airflow
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: scheduler
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - bash
        - -c
        - exec airflow scheduler
        env:
        - name: AIRFLOW_CONN_MINIO_S3
          value: aws://pachyderm:pachyderm-secret-key-123456789@/?region_name=us-east-1&extra__aws__endpoint_url=http%3A%2F%2Fminio.minio-tenant%3A80
        - name: AWS_ACCESS_KEY_ID
          value: pachyderm
        - name: AWS_SECRET_ACCESS_KEY
          value: pachyderm-secret-key-123456789
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              key: fernet-key
              name: airflow-fernet-key
        - name: AIRFLOW_HOME
          value: /opt/airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW_CONN_AIRFLOW_DB
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__API__SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: api-secret-key
              name: airflow-api-secret-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: airflow-jwt-secret
        image: apache/airflow:3.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
              airflow jobs check --job-type SchedulerJob --local
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 20
        name: scheduler
        ports:
        - containerPort: 8793
          name: worker-logs
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - |
              CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
              airflow jobs check --job-type SchedulerJob --local
          failureThreshold: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/pod_templates/pod_template_file.yaml
          name: config
          readOnly: true
          subPath: pod_template_file.yaml
        - mountPath: /opt/airflow/logs
          name: logs
        - mountPath: /opt/airflow/airflow.cfg
          name: config
          readOnly: true
          subPath: airflow.cfg
        - mountPath: /opt/airflow/config/airflow_local_settings.py
          name: config
          readOnly: true
          subPath: airflow_local_settings.py
        - mountPath: /opt/airflow/dags
          name: dags
      - args:
        - bash
        - /clean-logs
        env:
        - name: AIRFLOW__LOG_RETENTION_DAYS
          value: "15"
        - name: AIRFLOW__LOG_CLEANUP_FREQUENCY_MINUTES
          value: "15"
        - name: AIRFLOW_HOME
          value: /opt/airflow
        image: apache/airflow:3.1.0
        imagePullPolicy: IfNotPresent
        name: scheduler-log-groomer
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/logs
          name: logs
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - airflow
        - db
        - check-migrations
        - --migration-wait-timeout=60
        env:
        - name: AIRFLOW_CONN_MINIO_S3
          value: aws://pachyderm:pachyderm-secret-key-123456789@/?region_name=us-east-1&extra__aws__endpoint_url=http%3A%2F%2Fminio.minio-tenant%3A80
        - name: AWS_ACCESS_KEY_ID
          value: pachyderm
        - name: AWS_SECRET_ACCESS_KEY
          value: pachyderm-secret-key-123456789
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              key: fernet-key
              name: airflow-fernet-key
        - name: AIRFLOW_HOME
          value: /opt/airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW_CONN_AIRFLOW_DB
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__API__SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: api-secret-key
              name: airflow-api-secret-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: airflow-jwt-secret
        image: apache/airflow:3.1.0
        imagePullPolicy: IfNotPresent
        name: wait-for-airflow-migrations
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/airflow.cfg
          name: config
          readOnly: true
          subPath: airflow.cfg
        - mountPath: /opt/airflow/config/airflow_local_settings.py
          name: config
          readOnly: true
          subPath: airflow_local_settings.py
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 50000
      serviceAccount: airflow-scheduler
      serviceAccountName: airflow-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: airflow-config
        name: config
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags
      - emptyDir: {}
        name: logs
status:
  conditions:
  - lastTransitionTime: "2025-11-01T02:59:26Z"
    lastUpdateTime: "2025-11-01T02:59:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-01T02:51:42Z"
    lastUpdateTime: "2025-11-01T02:59:26Z"
    message: ReplicaSet "airflow-scheduler-655584879f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
