# file: docker/transcode/Dockerfile
FROM docker.io/jrottenberg/ffmpeg:8.0.3-ubuntu2404
RUN apt-get update && apt-get install -y python3 python3-pip curl jq awscli && rm -rf /var/lib/apt/lists/*

# Install pachctl for Pachyderm operations
RUN curl -L -o /usr/local/bin/pachctl https://github.com/pachyderm/pachyderm/releases/download/v2.12.2/pachctl_2.12.2_linux_amd64 && chmod +x /usr/local/bin/pachctl

COPY pfs_move.py /app/pfs_move.py
COPY transcode.py /app/transcode.py
WORKDIR /app
ENTRYPOINT ["python3","/app/transcode.py"]
