# file: docker/clamav/Dockerfile
FROM docker.io/clamav/clamav:1.5.4
RUN apk add --no-cache python3 py3-pip curl jq awscli

# Install pachctl for Pachyderm operations
RUN curl -L -o /usr/local/bin/pachctl https://github.com/pachyderm/pachyderm/releases/download/v2.12.2/pachctl_2.12.2_linux_amd64 && chmod +x /usr/local/bin/pachctl

COPY utils/ /app/utils/
COPY pfs_move.py /app/pfs_move.py
COPY scan.py /app/scan.py
WORKDIR /app
ENTRYPOINT ["python3","/app/scan.py"]
