# file: docker/validate/Dockerfile
FROM jrottenberg/ffmpeg:6.1-ubuntu
RUN apt-get update && apt-get install -y mediainfo python3 python3-pip curl jq awscli && rm -rf /var/lib/apt/lists/*
RUN curl -L https://github.com/pachyderm/pachyderm/releases/latest/download/pachctl_2.7.0_linux_amd64.tar.gz \
  | tar -xz && mv pachctl_*/pachctl /usr/local/bin/pachctl && rm -rf pachctl_*
COPY pfs_move.py /app/pfs_move.py
COPY validate.py /app/validate.py
WORKDIR /app
ENTRYPOINT ["python3","/app/validate.py"]